spring:
  application:
    name: telegram_bot
  config:
    import: classpath:config.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

binance:
  api:
    getPriceBitcoin: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT
    getPriceEthereum: https://api.binance.com/api/v3/avgPrice?symbol=ETHUSDT