spring:
  application:
    name: telegram_bot
  config:
    import: classpath:config.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  notify:
    delay:
      value: 10
      unit: MINUTES
  price-check:
    interval-ms: 120000

admin:
  id: ${ADMIN_ID}

binance:
  api:
    getPriceBitcoin: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT
    getPriceEthereum: https://api.binance.com/api/v3/avgPrice?symbol=ETHUSDT

rss:
  feed: https://cointelegraph.com/rss

facts:
  path: db/facts.json
  number: 12